### ISSUE TITLE
Fix the page layout in activity_main2.xml

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#1]
Change the layout of activity_main2.xml page components from Constraint Layout to Relative Layout for making it more adaptive to different screen sizes.

**Comment by sahil1678kumar** [comment]
I want to work on it

**Comment by Abhinavtdk** [comment]
I want to fix this

**Comment by supu2701** [comment]
> I want to work on it

@sahil1678kumar You have been assigned this issue. You can start working on it.
