### ISSUE TITLE
Replacing link with video

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#10]
Required changes to be made by inserting a video player in activity_disaster1.xml, activity_disaster2.xml, activity_disaster3.xml, activity_disaster4.xml so that the video link is replaced by the actual video that will be played at the same position. The video player  would fetch the video directly from YouTube( this would maintain the apk size i.e. it's size won't increse due to the addition of videos).

**Comment by shivjyotigarai** [comment]
can i work on it :)

**Comment by ASVKVINAYAK** [comment]
I want to fix this issue

**Comment by supu2701** [comment]
> can i work on it :)

You have been assigned this issue. You can start working on it.

**Comment by shivjyotigarai** [comment]
Can I start working on this issue 😊😊

**Comment by supu2701** [comment]
> Can I start working on this issue 😊😊

Yes, you can start working but make sure you create a different branch on your fork for this issue and create a new pull request.
