### ISSUE TITLE
Enable location dialog

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#11]
Addition of the feature of a dialog box which pops( in case the location service of the phone is initially turned off) just as one opens the app (i.e when the application is started) . the dialog will be as shown in the below image.
![WhatsApp Image 2020-12-10 at 6 36 16 PM](https://user-images.githubusercontent.com/58454886/101776370-d55ea100-3b16-11eb-8aee-7bc9c848d16f.jpeg)

**Comment by ASVKVINAYAK** [comment]
I want to fix this issue.

**Comment by supu2701** [comment]
> I want to fix this issue.

@ASVKVINAYAK You been assigned this issue. You can start working on it👍

**Comment by spacemonkey1101** [comment]
Is this issue still open? 
Will work on it if assigned.

**Comment by ASVKVINAYAK** [comment]
i have fixed the issue and please check it i have done correctly or not.
As my sem exams are from 18  so i was not able to respond earlier.

**Comment by supu2701** [comment]
> i have fixed the issue and please check it i have done correctly or not.
> As my sem exams are from 18 so i was not able to respond earlier.

Your PR has been reviewed and merged. Keep contributing👍
