### ISSUE TITLE
Swipe between activity

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#12]
Addition of swiping or sliding features between the four activity namely, activity_onboarding1.xml, activity_onboarding2.xml, activity_onboarding3.xml, activity_onboarding4.xml,. This will enable the user to move forward from one activity to another not only by the next button provided but also by swiping the screens.

**Comment by shivjyotigarai** [comment]
want to work on this 👍  :)

**Comment by shivjyotigarai** [comment]
would you plz assign this to me so that i could generate a pull request regarding the same.....  :)

**Comment by supu2701** [comment]
> would you plz assign this to me so that i could generate a pull request regarding the same..... :)
 
You have been assigned this issue. You can sart working on it👍

**Comment by shivjyotigarai** [comment]
> > would you plz assign this to me so that i could generate a pull request regarding the same..... :)
> 
> You have been assigned this issue. You can sart working on it👍

yeah

**Comment by shivjyotigarai** [comment]
pull request generated 👍

**Comment by supu2701** [comment]
> pull request generated 👍

@shivjyotigarai Great. You can also send a video or gif of the swiping activity.
