### ISSUE TITLE
Add a subsection in Nearby Services

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#13]
Add a subsection "Nearby Police Stations" in addition to the "Nearby Healthcare systems"(the design of the two subsection buttons would be similar to activity_social_platform.xml) in a activity. The click on "Nearby police station"  should take the user to an activity (similar to activity_maps) which will have a google map showing all the police stations nearby the current location of the user.

In addition to this, resolve the bug in the activity_maps page so as to make it properly functionable.

**Comment by pulkitchauhan03** [comment]
I want to do it

**Comment by supu2701** [comment]
> I want to do it

@pulkitchauhan03 You have been assigned this issue. You can start working on it👍

**Comment by supu2701** [comment]
@pulkitchauhan03 Please do complete fixing of this issue latest by tomorrow, otherwise it will be assigned to the next contributor. In case you are facing any doubts regarding this, you can ask on the channel.

**Comment by supu2701** [comment]
This issue is open now. Anyone who wants to fix this can comment as soon as possible.

**Comment by aashishat718** [comment]
@supu2701 I would like to take this issue.

**Comment by supu2701** [comment]
> @supu2701 I would like to take this issue.

@aashishat718 You have been assigned this issue. You can start working on it👍

**Comment by aashishat718** [comment]
@supu2701 Please refer to queries in slack channel.
