### ISSUE TITLE
Enhance "EMERGENCY CALL" Button

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#2]
Change the Button Background, Font Size, and enhance it to Rounded Corners of "EMERGENCY CALL" Button in activity_main2.xml page.

**Comment by shivjyotigarai** [comment]
want to fix this

**Comment by supu2701** [comment]
> want to fix this

The PR is currently in the review phase.

**Comment by sharmaumang001** [comment]
Is this closed ? or I can work on it?
