### ISSUE TITLE
Fixing of main2 Activity

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#24]
The following updations are required for activity_main2.xml page
1) Add the onclick task to the four icons as well, i.e the activities of "Send Alert Messages", "First aid". "Nearby Services" and "Precautionary steps" should open by clicking on its respective icons also and not just by clicking on the text field below the icon. 

2) Make the layouts of this activity in small, large and xlarge so that the the layout of the App is proper for Tablets and computer or any other bigger screen sizes.

3) Fix the landscape variation of this main2 activity so that on rotating the screen on mobile phone it do not appear so improper as shown in the screenshot below
![WhatsApp Image 2020-12-30 at 1 48 36 AM](https://user-images.githubusercontent.com/58454886/103311942-a36b9b00-4a41-11eb-98c2-2e1ae5ec88ec.jpeg)

**Comment by spacemonkey1101** [comment]
can i be assigned to this issue?

**Comment by supu2701** [comment]
> can i be assigned to this issue?

@spacemonkey1101 You have been assigned this issue. You can start working on it.
