### ISSUE TITLE
Changes in disaster1 and disaster2 and disaster4 activity

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#26]
The following changes are required for activity_disaster1.xml, activity_disaster4.xml and activity_disaster2.xml  
1) Change the layout of the page to a proper layout so that parts of the text do not either cut out of the activity or stands too close to the phone screen. Changes should be to ensure proper margin of the activity elements withe the screen end.
2) Make the layouts of this activity in small, large and xlarge so that the the layout of the App is proper for Tablets and computer or any other bigger screen sizes.
3) Fix the landscape variation of this main2 activity so that on rotating the screen on mobile phone it do not appear so improper as shown in the screenshot below

**Comment by ASVKVINAYAK** [comment]
Can I work on this issue

**Comment by supu2701** [comment]
> Can I work on this issue

@ASVKVINAYAK You have been assigned this issue. You can start working on it

**Comment by ASVKVINAYAK** [comment]
#30
