### ISSUE TITLE
Changes in activity_disaster3.xml

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#27]
The following changes are required in this activity:
1) Buttons having rounded corners and a light red color
2) Make the layouts of this activity in small, large and xlarge so that the the layout of the App is proper for Tablets and computer or any other bigger screen sizes.
3) Fix the landscape variation of this main2 activity so that on rotating the screen on mobile phone it do not appear so improper as shown in the screenshot below
![WhatsApp Image 2020-12-30 at 1 51 37 AM (2)](https://user-images.githubusercontent.com/58454886/103313414-019a7d00-4a46-11eb-9fdd-18fc27d7968d.jpeg)

**Comment by ASVKVINAYAK** [comment]
can i work on this issue

**Comment by supu2701** [comment]
> can i work on this issue

@ASVKVINAYAK You have been assigned this issue. You can start working on it.
