### ISSUE TITLE
Update content and background of activity_first_aid.xml page

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#3]
Add the following contents(as provided in the word file) on the page activity_first_aid.xml and change the background to #ABD46D
[First Aid Information.docx](https://github.com/supu2701/OTES-App/files/5622709/First.Aid.Information.docx)

**Comment by shivjyotigarai** [comment]
Here , while adding the following contents(as mentioned in the **docx** file) on **activity_first_aid.xml** , will i create different pages under **activity_first_aid1.xml** , **activity_first_aid2.xml** etc and then add the remaining information sequentially?


**_Attaching an appropriate screenshot_**

<img width="450" alt="Screenshot 2020-12-05 at 8 38 14 PM" src="https://user-images.githubusercontent.com/74768430/101246582-47f80700-373a-11eb-9ec0-8582cda0d56e.png">

**Comment by ASVKVINAYAK** [comment]
I want to fix this issue can i proceed .

**Comment by supu2701** [comment]
> Here , while adding the following contents(as mentioned in the **docx** file) on **activity_first_aid.xml** , will i create different pages under **activity_first_aid1.xml** , **activity_first_aid2.xml** etc and then add the remaining information sequentially?
> 
> **_Attaching an appropriate screenshot_**
> 
> <img alt="Screenshot 2020-12-05 at 8 38 14 PM" width="450" src="https://user-images.githubusercontent.com/74768430/101246582-47f80700-373a-11eb-9ec0-8582cda0d56e.png">

No, all the contents of the docx file should be activity_first_aid.xml page itself. It should continue the sequence of the two first aids already mentioned. Do not worry if the content is not visible and goes outside the page layout screen on Android Studio as it will be fixed later by attaching a scroll bar.

**Comment by supu2701** [comment]
> I want to fix this issue can i proceed .

You have been assigned this issue. You can start working on it.

**Comment by shivjyotigarai** [comment]
is the issue fixed?

**Comment by ASVKVINAYAK** [comment]
Yes I have fixed and made a pull request please check it.

**Comment by shivjyotigarai** [comment]
> Yes I have fixed and made a pull request please check it.

yeah...
