### ISSUE TITLE
Update the .gitignore file

### ISSUE THREAD

**Issue by supu2701** [supu2701/OTES-App#7]
Update the .gitignore file to the following and run the necessary commands to prevent the newly added file into .gitignore file from being tracked.

````
# Built application files
/*/build/

# Crashlytics configuations
com_crashlytics_export_strings.xml

# Local configuration file (sdk path, etc)
local.properties

# Gradle generated files
.gradle/

# Signing files
.signing/

# User-specific configurations
.idea/libraries/
.idea/workspace.xml
.idea/tasks.xml
.idea/.name
.idea/compiler.xml
.idea/copyright/profiles_settings.xml
.idea/encodings.xml
.idea/misc.xml
.idea/modules.xml
.idea/scopes/scope_settings.xml
.idea/vcs.xml
*.iml

# OS-specific files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
````

You can then used the following comment to prevent git from tracking them.
````git rm -r --cached .````
then just run
````git add .````
and
````git commit -m ".gitignore is working"````

**Comment by sahil1678kumar** [comment]
What is this issue exactly?
Can you please elaborate?

**Comment by shivjyotigarai** [comment]
plz elaborate...couldnt understand well

**Comment by ASVKVINAYAK** [comment]
I want to fix this issue but cannot understand it
Can you explain what I have to do exactly it would be helpful.

**Comment by spacemonkey1101** [comment]
can you assign me this?

**Comment by supu2701** [comment]
The issue is that currently some unnecessary files (like .idea/ etc ) are not being ignored by git as per our current .gitignore file. This causes these files to be included in pull requests which sommetimes results in conflicts. So, all I want is to update the contents of .gitignore file to the one provided above , commit the changes and then run the above or any other relevent commands to prevent the git from further tracking the unnecessary files (which was previously not included in .gitignore).

**Comment by ASVKVINAYAK** [comment]
Ok I have updated the .gitignore file with the given data and run the required git commands and made a pull request please check it I have done correctly or not.

**Comment by supu2701** [comment]
> Ok I have updated the .gitignore file with the given data and run the required git commands and made a pull request please check it I have done correctly or not.

@ASVKVINAYAK . Your PR has been reviewed. But, a small reminder. Do not start working on a issue unless you are assigned so as to avoid the conflicting situation where more than one person will be working on the same issue. In that case, someone's time and efforts can get wasted. 
Anyways congratulations and keep contributing.

**Comment by ASVKVINAYAK** [comment]
Ok
 I was a bit excited to solve the issues So I tried.
From Next time I will remember this .
